// <auto-generated />
namespace ToDoApp12329.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TeamMembersDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TeamMembersDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202102241711121_TeamMembersDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
